# CLick Through Rate Assignment

<br>
Author          :   Phuc Thanh Nguyen
<br>
Created         :   Feb 4th, 2023     
<br>
Last edited     :   Feb 5th, 2023

## Import libraries and define paths

In [1]:
#--------------------------------------------------------------------------
# Import libraries
#--------------------------------------------------------------------------
import      os
import      numpy               as      np
import      pandas              as      pd
import      matplotlib.pyplot   as      plt

In [2]:
#--------------------------------------------------------------------------
# Define paths of data
#--------------------------------------------------------------------------
description_path    =   '/home/ptn/Others/Learning/UoA/Course 03:  Introduction to Machine Learning/Module_05_Click_Through_Rate_Prediction_Assignment/data/Data+Description+-+Sheet1 (1).csv'
data_path           =   '/home/ptn/Others/Learning/UoA/Course 03:  Introduction to Machine Learning/Module_05_Click_Through_Rate_Prediction_Assignment/data/data (1).csv'

## EDA

### Take a look as data

#### Data description

In [3]:
#--------------------------------------------------------------------------
# Data description
#--------------------------------------------------------------------------
des_cf = pd.read_csv(description_path)
des_cf

,Variable,Description
0,click:,0/1 for non-click/click
1,"hour: format is YYMMDDHH, so 14091123 means 23...",NaN
2,C1,anonymized categorical variable
3,banner_pos,position of the ad/banner on the page
4,site_id,unique id of the site on which the ad is shown
5,site_domain,unique domain of the site on which the ad is s...
6,site_category,category of the site on which the ad is shown
7,app_id,app id of the site on which the ad is shown
8,app_domain,app category of the site on which the ad is shown
9,app_category,category id of the site on which the ad is shown
10,device_id,device id on which the add was shown
11,device_ip,ip address of the device on which the ad was s...
12,device_model,model type of the device on which the ad was s...
13,device_type,the device type on which the ad was shown
14,device_conn_type,the connection type of the device on which the...
15,C14 - C21,anonymized categorical variable

<b> click </b> is our target variable

### Data

In [4]:
#--------------------------------------------------------------------------
# Load data
#--------------------------------------------------------------------------
df  =   pd.read_csv(data_path)
print('Shape of data: {}'.format(df.shape))
df.head(5)

Shape of data: (99999, 27)

,click,C1,banner_pos,site_id,site_domain,site_category,app_id,app_domain,app_category,device_id,...,C17,C18,C19,C20,C21,month,dayofweek,day,hour,y
0,False,1005,1,856e6d3f,58a89a43,f028772b,ecad2386,7801e8d9,07d7df22,a99f214a,...,2528,0,39,100075,221,10,1,28,14,0
1,True,1005,1,e151e245,7e091613,f028772b,ecad2386,7801e8d9,07d7df22,a99f214a,...,1934,2,39,-1,16,10,2,22,19,1
2,False,1005,0,e3c09f3a,d262cf1e,28905ebd,ecad2386,7801e8d9,07d7df22,a99f214a,...,2552,3,167,100202,23,10,3,23,18,0
3,False,1002,0,0da94452,248e439f,50e219e0,ecad2386,7801e8d9,07d7df22,0fa578fd,...,2478,3,167,100074,23,10,2,22,19,0
4,True,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,07d7df22,a99f214a,...,1722,0,35,-1,79,10,1,21,8,1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99999 entries, 0 to 99998
Data columns (total 27 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   click             99999 non-null  bool
 1   C1                99999 non-null  int64
 2   banner_pos        99999 non-null  int64
 3   site_id           99999 non-null  object
 4   site_domain       99999 non-null  object
 5   site_category     99999 non-null  object
 6   app_id            99999 non-null  object
 7   app_domain        99999 non-null  object
 8   app_category      99999 non-null  object
 9   device_id         99999 non-null  object
 10  device_ip         99999 non-null  object
 11  device_model      99999 non-null  object
 12  device_type       99999 non-null  int64
 13  device_conn_type  99999 non-null  int64
 14  C14               99999 non-null  int64
 15  C15               99999 non-null  int64
 16  C16               99999 non-null  int64
 17  C17               99999 non-null  int64
 18  C18               99999 non-null  int64
 19  C19               99999 non-null  int64
 20  C20               99999 non-null  int64
 21  C21               99999 non-null  int64
 22  month             99999 non-null  int64
 23  dayofweek         99999 non-null  int64
 24  day               99999 non-null  int64
 25  hour              99999 non-null  int64
 26  y                 99999 non-null  int64
dtypes: bool(1), int64(17), object(9)
memory usage: 19.9+ MB

In [7]:
df.nunique()

click                   2
C1                      7
banner_pos              7
site_id              1485
site_domain          1331
site_category          19
app_id               1354
app_domain             96
app_category           21
device_id           16801
device_ip           78013
device_model         3145
device_type             4
device_conn_type        4
C14                  1722
C15                     8
C16                     9
C17                   399
C18                     4
C19                    64
C20                   154
C21                    60
month                   1
dayofweek               7
day                    10
hour                   24
y                       2
dtype: int64

In [6]:
df.nunique()/df.shape[0]*100

click                0.002000
C1                   0.007000
banner_pos           0.007000
site_id              1.485015
site_domain          1.331013
site_category        0.019000
app_id               1.354014
app_domain           0.096001
app_category         0.021000
device_id           16.801168
device_ip           78.013780
device_model         3.145031
device_type          0.004000
device_conn_type     0.004000
C14                  1.722017
C15                  0.008000
C16                  0.009000
C17                  0.399004
C18                  0.004000
C19                  0.064001
C20                  0.154002
C21                  0.060001
month                0.001000
dayofweek            0.007000
day                  0.010000
hour                 0.024000
y                    0.002000
dtype: float64

In [ ]:
numerical_columns   =   ['month', 'dayofweek', 'day', 'hour']
categorical_columns =   ['C1', 'banner_pos', 'site_id', 'site_domain', 'site_category', 'app_id', 'app_domain', 'app_category', 'device_id', 'device_ip', 'device_model', 'device_type', 'device_conn_type', 'C14', 'C15', 'C16', 'C17', 'C18', 'C19', 'C20', 'C21']

We see that some categorical have a lot of unique

### Deal with missing data

In [ ]:
#--------------------------------------------------------------------------
# Check missing in row and print
#--------------------------------------------------------------------------
null_data = df[df.isnull().any(axis=1)]
null_data

In [ ]:
#--------------------------------------------------------------------------
# Check missing in col and print
#--------------------------------------------------------------------------
df.isnull().sum()

<b> We see that there is no missing value here

### Univariate analysis

#### Deal with outliers

In [ ]:
#--------------------------------------------------------------------------
# Find outlier function
#--------------------------------------------------------------------------
def find_outlier(df, col_name, plot = True):
    """
        Find outliers of numerical data
        Input:
            .df         :   Dataframe
            .col_name   :   Column name
            .plot       :   Box plot
        Output
            .outliers   :   Outliers in df
    """
    
    
    #--------------------------------------------------------------------------
    # Find outlier part
    #--------------------------------------------------------------------------
    
    df          =   df[col_name]
    q1          =   df.quantile(0.25)
    q3          =   df.quantile(0.75)
    IQR         =   q3-q1
    outliers    =   df[((df<(q1-1.5*IQR)) | (df>(q3+1.5*IQR)))]
    

    #--------------------------------------------------------------------------
    # Plot part
    #--------------------------------------------------------------------------

    plt.boxplot(df)


    return outliers

### Bivariate analysis